/// Flutter icons RHomeIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RHomeIcon
///      fonts:
///       - asset: fonts/RHomeIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RHomeIcon {
  RHomeIcon._();

  static const _kFontFam = 'RHomeIcon';
  static const String? _kFontPkg = null;

  static const IconData against = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bitcoin = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ether = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eurs = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favour = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData irrelevant = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reward = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData token = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData disputes = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
